<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Schema;

class O_Inspeccion extends Model
{
    use HasFactory;

    protected $table = 'o_inspeccion';
     /**
     * Indica si el modelo debe mantener los timestamps.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id_sucursal',
        'orden',
        'nomina',
        'nuevo',
        'vivo',
        'modificado',
        'reply',
        'id_placa',
        'id_cliente',
        'afinacion',
        'filtro_aire',
        'filtro_gas',
        'bujias',
        'pvc',
        'humo',
        'gases',
        'tapon_aceite',
        'bayoneta',
        'reseteo',
        'sus_eje',
        'sus_rotu',
        'sus_hules',
        'sus_bujes',
        'sus_horqui',
        'sus_mangos',
        'sus_pitman',
        'sus_aux',
        'sus_homo',
        'sus_resortes',
        'dire_bomba',
        'dire_polvo',
        'dire_crema',
        'dire_varillas',
        'dire_termina',
        'amor_fuga',
        'amor_golpe',
        'amor_spresion',
        'amor_reem',
        'daceite_bajo',
        'daceite_contami',
        'escape_roto',
        'escape_fugas',
        'cata_roto',
        'cata_degra',
        'cata_reem',
        'fugas_refri',
        'fugas_aceite',
        'fugas_frenos',
        'fugas_dire',
        'fugas_tran',
        'suspension',
        'direccion',
        'amortigua',
        'aceite_dif',
        'sis_escape',
        'catalitico',
        'fugas',
        'aceite_bajo',
        'aceite_degradado',
        'refri_bajo',
        'refri_degradado',
        'sumang_reseca',
        'sumang_agrie',
        'sumang_rota',
        'inmang_reseca',
        'inmang_agrie',
        'inmang_rota',
        'banda_reseca',
        'banda_agrie',
        'banda_rota',
        'bate_bajo',
        'bate_corto',
        'bate_rota',
        'alterna_ruido',
        'alterna_especi',
        'atrans_bajo',
        'atrans_degra',
        'adire_bajo',
        'adire_degra',
        'liq_bajo',
        'liq_degra',
        'somotor_roto',
        'somotor_suelto',
        'sotrans_roto',
        'sotrans_suelto',
        'reseteo_cofre',
        'aceite',
        'refrigerante',
        'manguera_su',
        'manguera_inf',
        'banda',
        'bateria',
        'alternador',
        'transmision',
        'limpiapara',
        'so_motor',
        'so_transmision',
        'direccion_cofre',
        'luz_dd_alta',
        'luz_dd_baja',
        'luz_dd_cuarto',
        'luz_dd_dire',
        'luz_di_alta',
        'luz_di_baja',
        'luz_di_cuarto',
        'luz_di_dire',
        'luz_td_cuarto',
        'luz_td_stop',
        'luz_td_rever',
        'luz_td_dire',
        'luz_ti_cuarto',
        'luz_ti_stop',
        'luz_ti_rever',
        'luz_ti_dire',
        'luz_emer',
        'limpia_liq',
        'limpia_hules',
        'limpia_rocia',
        'ot_espe',
        'ot_ante',
        'ot_cris',
        'ot_moldu',
        'ot_carro',
        'ot_micas',
        'luces_dd',
        'luces_di',
        'luces_td',
        'luces_ti',
        'luces_eme',
        'limpiabrisas',
        'otros',
        'bomba',
        'balatas',
        'disco',
        'tambores',
        'pistones',
        'cilindros',
        'booster',
        'liquido',
        'calipers',
        'tubos',
        'mangueras',
        'frenomano',
        'ajuste',
        'limpieza',
        'frenos',
        'luces_tablero',
        'luces_cortesia',
        'luces_puerta',
        'airea_noenfria',
        'airea_conflujo',
        'aire_mante',
        'cabina_sucio',
        'cabina_reemplaza',
        'claxon_nofun',
        'claxon_anormal',
        'equipo_espejo',
        'equipo_viseras',
        'equipo_radio',
        'equipo_seguros',
        'equipo_eleva',
        'equipo_cinturon',
        'ck_iconos',
        'iconos',
        'luces',
        'aire',
        'cabina',
        'claxon',
        'equipo',
        'txt_iconos',
        'txt_otros',
        'alineacion',
        'balanceo',
        'rotacion',
        'reemplazo',
        'desgaste_dd',
        'desgaste_di',
        'desgaste_td',
        'desgaste_ti',
        'desgaste_ref',
        'presion_di_a',
        'presion_di_d',
        'presion_dd_a',
        'presion_dd_d',
        'presion_ti_a',
        'presion_ti_d',
        'presion_td_a',
        'presion_td_d',
        'presion_ref_a',
        'presion_ref_d',
        'gato',
        'torque',
        'otros_llantas',
        'id',
        'fh_creacion',
        'observaciones',
        'fecha_llanta',
        'fecha_freno',
        'fecha_afinacion',
        'fecha_interior',
        'fecha_bajo',
        'fecha_cofre',
        'fecha_exterior',
        'txt_ofrece',
        'txt_solicita',
        'cotizacion_interior',
        'cotizacion_auto',
        'cotizacion_exterior',
        'cotizacion_cofre',
        'cotizacion_llantas',
        'cotizacion_afinacion',
        'cotizacion_frenos',
        'golpes_di',
        'clavos_di',
        'bolas_di',
        'corta_di',
        'desgas_di',
        'golpes_dd',
        'clavos_dd',
        'bolas_dd',
        'corta_dd',
        'desgas_dd',
        'golpes_td',
        'clavos_td',
        'bolas_td',
        'corta_td',
        'desgas_td',
        'golpes_ti',
        'clavos_ti',
        'bolas_ti',
        'corta_ti',
        'desgas_ti',
        'golpes_ref',
        'clavos_ref',
        'bolas_ref',
        'corta_ref',
        'desgas_ref',
        'ck_final',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    // Actualizar esta tabla cada vez que se actualice un campo en la tabla
    protected $casts = [
        'id_sucursal' => 'integer',
        'orden' => 'integer',
        'nomina' => 'integer',
        'nuevo' => 'boolean',
        'vivo' => 'boolean',
        'modificado' => 'boolean',
        'reply' => 'boolean',
        'id_placa' => 'integer',
        'id_cliente' => 'integer',
        'afinacion' => 'integer',
        'filtro_aire' => 'integer',
        'filtro_gas' => 'integer',
        'bujias' => 'integer',
        'pvc' => 'integer',
        'humo' => 'integer',
        'gases' => 'integer',
        'tapon_aceite' => 'integer',
        'bayoneta' => 'integer',
        'reseteo' => 'boolean',
        'sus_eje' => 'boolean',
        'sus_rotu' => 'boolean',
        'sus_hules' => 'boolean',
        'sus_bujes' => 'boolean',
        'sus_horqui' => 'boolean',
        'sus_mangos' => 'boolean',
        'sus_pitman' => 'boolean',
        'sus_aux' => 'boolean',
        'sus_homo' => 'boolean',
        'sus_resortes' => 'boolean',
        'dire_bomba' => 'boolean',
        'dire_polvo' => 'boolean',
        'dire_crema' => 'boolean',
        'dire_varillas' => 'boolean',
        'dire_termina' => 'boolean',
        'amor_fuga' => 'boolean',
        'amor_golpe' => 'boolean',
        'amor_spresion' => 'boolean',
        'amor_reem' => 'boolean',
        'daceite_bajo' => 'boolean',
        'daceite_contami' => 'boolean',
        'escape_roto' => 'boolean',
        'escape_fugas' => 'boolean',
        'cata_roto' => 'boolean',
        'cata_degra' => 'boolean',
        'cata_reem' => 'boolean',
        'fugas_refri' => 'boolean',
        'fugas_aceite' => 'boolean',
        'fugas_frenos' => 'boolean',
        'fugas_dire' => 'boolean',
        'fugas_tran' => 'boolean',
        'suspension' => 'integer',
        'direccion' => 'integer',
        'amortigua' => 'integer',
        'aceite_dif' => 'integer',
        'sis_escape' => 'integer',
        'catalitico' => 'integer',
        'fugas' => 'integer',
        'aceite_bajo' => 'boolean',
        'aceite_degradado' => 'boolean',
        'refri_bajo' => 'boolean',
        'refri_degradado' => 'boolean',
        'sumang_reseca' => 'boolean',
        'sumang_agrie' => 'boolean',
        'sumang_rota' => 'boolean',
        'inmang_reseca' => 'boolean',
        'inmang_agrie' => 'boolean',
        'inmang_rota' => 'boolean',
        'banda_reseca' => 'boolean',
        'banda_agrie' => 'boolean',
        'banda_rota' => 'boolean',
        'bate_bajo' => 'boolean',
        'bate_corto' => 'boolean',
        'bate_rota' => 'boolean',
        'alterna_ruido' => 'boolean',
        'alterna_especi' => 'boolean',
        'atrans_bajo' => 'boolean',
        'atrans_degra' => 'boolean',
        'adire_bajo' => 'boolean',
        'adire_degra' => 'boolean',
        'liq_bajo' => 'boolean',
        'liq_degra' => 'boolean',
        'somotor_roto' => 'boolean',
        'somotor_suelto' => 'boolean',
        'sotrans_roto' => 'boolean',
        'sotrans_suelto' => 'boolean',
        'reseteo_cofre' => 'boolean',
        'aceite' => 'integer',
        'refrigerante' => 'integer',
        'manguera_su' => 'integer',
        'manguera_inf' => 'integer',
        'banda' => 'integer',
        'bateria' => 'integer',
        'alternador' => 'integer',
        'transmision' => 'integer',
        'limpiapara' => 'integer',
        'so_motor' => 'integer',
        'so_transmision' => 'integer',
        'direccion_cofre' => 'integer',
        'luz_dd_alta' => 'boolean',
        'luz_dd_baja' => 'boolean',
        'luz_dd_cuarto' => 'boolean',
        'luz_dd_dire' => 'boolean',
        'luz_di_alta' => 'boolean',
        'luz_di_baja' => 'boolean',
        'luz_di_cuarto' => 'boolean',
        'luz_di_dire' => 'boolean',
        'luz_td_cuarto' => 'boolean',
        'luz_td_stop' => 'boolean',
        'luz_td_rever' => 'boolean',
        'luz_td_dire' => 'boolean',
        'luz_ti_cuarto' => 'boolean',
        'luz_ti_stop' => 'boolean',
        'luz_ti_rever' => 'boolean',
        'luz_ti_dire' => 'boolean',
        'luz_emer' => 'boolean',
        'limpia_liq' => 'boolean',
        'limpia_hules' => 'boolean',
        'limpia_rocia' => 'boolean',
        'ot_espe' => 'boolean',
        'ot_ante' => 'boolean',
        'ot_cris' => 'boolean',
        'ot_moldu' => 'boolean',
        'ot_carro' => 'boolean',
        'ot_micas' => 'boolean',
        'luces_dd' => 'integer',
        'luces_di' => 'integer',
        'luces_td' => 'integer',
        'luces_ti' => 'integer',
        'luces_eme' => 'integer',
        'limpiabrisas' => 'integer',
        'otros' => 'integer',
        'bomba' => 'boolean',
        'balatas' => 'boolean',
        'disco' => 'boolean',
        'tambores' => 'boolean',
        'pistones' => 'boolean',
        'cilindros' => 'boolean',
        'booster' => 'boolean',
        'liquido' => 'boolean',
        'calipers' => 'boolean',
        'tubos' => 'boolean',
        'mangueras' => 'boolean',
        'frenomano' => 'boolean',
        'ajuste' => 'boolean',
        'limpieza' => 'boolean',
        'frenos' => 'integer',
        'luces_tablero' => 'boolean',
        'luces_cortesia' => 'boolean',
        'luces_puerta' => 'boolean',
        'airea_noenfria' => 'boolean',
        'airea_conflujo' => 'boolean',
        'aire_mante' => 'boolean',
        'cabina_sucio' => 'boolean',
        'cabina_reemplaza' => 'boolean',
        'claxon_nofun' => 'boolean',
        'claxon_anormal' => 'boolean',
        'equipo_espejo' => 'boolean',
        'equipo_viseras' => 'boolean',
        'equipo_radio' => 'boolean',
        'equipo_seguros' => 'boolean',
        'equipo_eleva' => 'boolean',
        'equipo_cinturon' => 'boolean',
        'ck_iconos' => 'boolean',
        'iconos' => 'integer',
        'luces' => 'integer',
        'aire' => 'integer',
        'cabina' => 'integer',
        'claxon' => 'integer',
        'equipo' => 'integer',
        'txt_iconos' => 'string',
        'txt_otros' => 'string',
        'alineacion' => 'integer',
        'balanceo' => 'integer',
        'rotacion' => 'integer',
        'reemplazo' => 'integer',
        'desgaste_dd' => 'integer',
        'desgaste_di' => 'integer',
        'desgaste_td' => 'integer',
        'desgaste_ti' => 'integer',
        'desgaste_ref' => 'integer',
        'presion_di_a' => 'integer',
        'presion_di_d' => 'integer',
        'presion_dd_a' => 'integer',
        'presion_dd_d' => 'integer',
        'presion_ti_a' => 'integer',
        'presion_ti_d' => 'integer',
        'presion_td_a' => 'integer',
        'presion_td_d' => 'integer',
        'presion_ref_a' => 'integer',
        'presion_ref_d' => 'integer',
        'gato' => 'boolean',
        'torque' => 'boolean',
        'otros_llantas' => 'boolean',
        'id' => 'integer',
        'fh_creacion' => 'timestamp',
        'observaciones' => 'string',
        'fecha_llanta' => 'datetime',
        'fecha_freno' => 'datetime',
        'fecha_afinacion' => 'datetime',
        'fecha_interior' => 'datetime',
        'fecha_bajo' => 'datetime',
        'fecha_cofre' => 'datetime',
        'fecha_exterior' => 'datetime',
        'txt_ofrece' => 'string',
        'txt_solicita' => 'string',
        'cotizacion_interior' => 'string',
        'cotizacion_auto' => 'string',
        'cotizacion_exterior' => 'string',
        'cotizacion_cofre' => 'string',
        'cotizacion_llantas' => 'string',
        'cotizacion_afinacion' => 'string',
        'cotizacion_frenos' => 'string',
        'golpes_di' => 'boolean',
        'clavos_di' => 'boolean',
        'bolas_di' => 'boolean',
        'corta_di' => 'boolean',
        'desgas_di' => 'boolean',
        'golpes_dd' => 'boolean',
        'clavos_dd' => 'boolean',
        'bolas_dd' => 'boolean',
        'corta_dd' => 'boolean',
        'desgas_dd' => 'boolean',
        'golpes_td' => 'boolean',
        'clavos_td' => 'boolean',
        'bolas_td' => 'boolean',
        'corta_td' => 'boolean',
        'desgas_td' => 'boolean',
        'golpes_ti' => 'boolean',
        'clavos_ti' => 'boolean',
        'bolas_ti' => 'boolean',
        'corta_ti' => 'boolean',
        'desgas_ti' => 'boolean',
        'golpes_ref' => 'boolean',
        'clavos_ref' => 'boolean',
        'bolas_ref' => 'boolean',
        'corta_ref' => 'boolean',
        'desgas_ref' => 'boolean',
        'ck_final' => 'boolean',
    ];

    /**
     * The attributes that should have default values.
     *
     * @var array
     */
    protected $attributes = [
        'vivo' => true,
        'ck_final' => false,
        "nuevo" => true,
        "modificado" => false,
        "reply" => false,
    ];
}



